import { UnifiedPersona } from '@shared/mockupTypes';

export const TEEN_PERSONAS: UnifiedPersona[] = [
  {
    id: 'teen-female-white-s-01',
    name: 'Emma',
    age: '15',
    sex: 'Female',
    ethnicity: 'White',
    size: 'S',
    height: "5'3\"",
    weight: '110 lbs',
    build: 'slim',
    facialFeatures: 'youthful face, clear skin',
    hairStyle: 'long straight',
    hairColor: 'blonde',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Bright 15-year-old girl with a slim build and youthful energy. Her long straight blonde hair frames a fresh face with clear skin and bright blue eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-female-black-s-01',
    name: 'Zoe',
    age: '14',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'S',
    height: "5'2\"",
    weight: '105 lbs',
    build: 'slender',
    facialFeatures: 'bright eyes, cheerful expression',
    hairStyle: 'curly natural',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Energetic 14-year-old girl with a slender build and infectious enthusiasm. Her natural curly black hair bounces with movement, with bright dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-female-hispanic-m-01',
    name: 'Isabella',
    age: '16',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'M',
    height: "5'4\"",
    weight: '125 lbs',
    build: 'average',
    facialFeatures: 'warm smile, expressive features',
    hairStyle: 'medium wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'olive',
    fullDescription: 'Friendly 16-year-old girl with an average build and warm personality. Her medium-length wavy dark brown hair complements her olive skin and expressive brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-female-asian-m-01',
    name: 'Lily',
    age: '15',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'M',
    height: "5'3\"",
    weight: '115 lbs',
    build: 'petite athletic',
    facialFeatures: 'delicate features, studious look',
    hairStyle: 'long straight with bangs',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Studious 15-year-old girl with a petite athletic build. Her long straight black hair with bangs frames delicate features and thoughtful dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-female-indian-m-01',
    name: 'Asha',
    age: '17',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'M',
    height: "5'4\"",
    weight: '120 lbs',
    build: 'slim',
    facialFeatures: 'bright smile, soft features',
    hairStyle: 'long braided',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'warm brown',
    fullDescription: 'Cheerful 17-year-old girl with a slim build and bright smile. Her long dark brown hair is often worn in a neat braid, with soft features and warm brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-female-southeast-asian-s-01',
    name: 'Mai',
    age: '14',
    sex: 'Female',
    ethnicity: 'Southeast Asian',
    size: 'S',
    height: "5'1\"",
    weight: '100 lbs',
    build: 'petite',
    facialFeatures: 'round face, sweet expression',
    hairStyle: 'medium straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light tan',
    fullDescription: 'Sweet 14-year-old girl with a petite build and gentle demeanor. Her medium-length straight black hair frames a round face with a kind expression and dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-white-s-01',
    name: 'Jake',
    age: '14',
    sex: 'Male',
    ethnicity: 'White',
    size: 'S',
    height: "5'4\"",
    weight: '115 lbs',
    build: 'lean',
    facialFeatures: 'youthful features, light freckles',
    hairStyle: 'short messy',
    hairColor: 'light brown',
    eyeColor: 'hazel',
    skinTone: 'fair with freckles',
    fullDescription: 'Energetic 14-year-old boy with a lean build and youthful enthusiasm. His short messy light brown hair and light freckles give him a boyish charm, with curious hazel eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-black-m-01',
    name: 'Marcus',
    age: '16',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'M',
    height: "5'8\"",
    weight: '145 lbs',
    build: 'athletic',
    facialFeatures: 'confident expression, defined jaw',
    hairStyle: 'short fade',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'dark brown',
    fullDescription: 'Confident 16-year-old boy with an athletic build from sports. His clean short fade is neatly maintained, with a defined jaw and focused dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-hispanic-m-01',
    name: 'Diego',
    age: '15',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'M',
    height: "5'6\"",
    weight: '135 lbs',
    build: 'average',
    facialFeatures: 'friendly face, easy smile',
    hairStyle: 'medium wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'tan',
    fullDescription: 'Friendly 15-year-old boy with an average build and easy-going nature. His medium wavy dark brown hair has natural volume, with warm brown eyes and an easy smile.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-asian-s-01',
    name: 'Ryan',
    age: '13',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'S',
    height: "5'2\"",
    weight: '100 lbs',
    build: 'slim',
    facialFeatures: 'youthful, bright expression',
    hairStyle: 'short straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Curious 13-year-old boy with a slim build and bright expression. His short straight black hair is neatly styled, with alert dark brown eyes full of curiosity.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-indian-m-01',
    name: 'Arjun',
    age: '17',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'M',
    height: "5'9\"",
    weight: '150 lbs',
    build: 'lean athletic',
    facialFeatures: 'angular features, focused look',
    hairStyle: 'short textured',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Focused 17-year-old boy with a lean athletic build. His short textured black hair is casually styled, with angular features and determined dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-indigenous-m-01',
    name: 'Noah',
    age: '16',
    sex: 'Male',
    ethnicity: 'Indigenous',
    size: 'M',
    height: "5'7\"",
    weight: '140 lbs',
    build: 'solid',
    facialFeatures: 'strong features, thoughtful expression',
    hairStyle: 'medium straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Thoughtful 16-year-old boy with a solid build and quiet strength. His medium-length straight black hair frames strong features and deep thoughtful dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-female-middle-eastern-m-01',
    name: 'Yasmine',
    age: '15',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'M',
    height: "5'4\"",
    weight: '115 lbs',
    build: 'slim',
    facialFeatures: 'elegant features, warm expression',
    hairStyle: 'long wavy',
    hairColor: 'dark brown',
    eyeColor: 'dark brown',
    skinTone: 'warm olive',
    fullDescription: 'A 15-year-old Middle Eastern teen with a slim build and graceful presence. Her long wavy dark brown hair frames elegant features with warm olive skin and expressive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'teen-male-middle-eastern-m-01',
    name: 'Amir',
    age: '16',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'M',
    height: "5'8\"",
    weight: '145 lbs',
    build: 'lean athletic',
    facialFeatures: 'olive skin, defined brows, expressive dark eyes',
    hairStyle: 'short textured',
    hairColor: 'dark brown',
    eyeColor: 'dark brown',
    skinTone: 'warm olive',
    fullDescription: 'A 16-year-old Middle Eastern teen with a lean athletic build and confident demeanor. His short textured dark brown hair is neatly styled, with defined brows and expressive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  }
];
