import { UnifiedPersona } from '@shared/mockupTypes';

export const YOUNG_ADULT_PERSONAS: UnifiedPersona[] = [
  {
    id: 'young-adult-female-white-s-01',
    name: 'Emma',
    age: '21',
    sex: 'Female',
    ethnicity: 'White',
    size: 'S',
    height: "5'4\"",
    weight: '115 lbs',
    build: 'slim athletic',
    facialFeatures: 'heart-shaped face, bright eyes',
    hairStyle: 'long beachy waves',
    hairColor: 'light brown',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Vibrant 21-year-old woman with a slim athletic build from regular yoga. Her long beachy waves of light brown hair frame a heart-shaped face with bright blue eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-black-s-01',
    name: 'Aaliyah',
    age: '19',
    sex: 'Female',
    ethnicity: 'Black',
    size: 'S',
    height: "5'5\"",
    weight: '120 lbs',
    build: 'slender',
    facialFeatures: 'high cheekbones, radiant smile',
    hairStyle: 'long box braids',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'rich brown',
    fullDescription: 'Radiant 19-year-old woman with a slender build and confident presence. Her long box braids frame high cheekbones and a dazzling smile, with expressive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-hispanic-m-01',
    name: 'Valentina',
    age: '23',
    sex: 'Female',
    ethnicity: 'Hispanic',
    size: 'M',
    height: "5'5\"",
    weight: '135 lbs',
    build: 'toned curves',
    facialFeatures: 'warm features, expressive eyes',
    hairStyle: 'long curly',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'warm olive',
    fullDescription: 'Charismatic 23-year-old woman with toned curves and natural beauty. Her long curly dark brown hair cascades beautifully, with warm features and expressive brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-asian-m-01',
    name: 'Jessica',
    age: '22',
    sex: 'Female',
    ethnicity: 'Asian',
    size: 'M',
    height: "5'4\"",
    weight: '125 lbs',
    build: 'balanced',
    facialFeatures: 'delicate features, warm smile',
    hairStyle: 'medium length with highlights',
    hairColor: 'black with brown highlights',
    eyeColor: 'dark brown',
    skinTone: 'light golden',
    fullDescription: 'Friendly 22-year-old woman with a balanced build and approachable demeanor. Her medium-length black hair with brown highlights frames delicate features and a warm smile.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-indian-l-01',
    name: 'Priya',
    age: '24',
    sex: 'Female',
    ethnicity: 'Indian',
    size: 'L',
    height: "5'5\"",
    weight: '150 lbs',
    build: 'curvy',
    facialFeatures: 'expressive eyes, bright smile',
    hairStyle: 'long straight',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'warm caramel',
    fullDescription: 'Confident 24-year-old woman with beautiful curves and radiant presence. Her long straight dark brown hair and warm caramel skin complement expressive brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-southeast-asian-s-01',
    name: 'Kim',
    age: '20',
    sex: 'Female',
    ethnicity: 'Southeast Asian',
    size: 'S',
    height: "5'2\"",
    weight: '105 lbs',
    build: 'petite',
    facialFeatures: 'youthful features, gentle expression',
    hairStyle: 'long straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light tan',
    fullDescription: 'Sweet 20-year-old woman with a petite build and gentle demeanor. Her long straight black hair is sleek and shiny, with youthful features and kind dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-indigenous-m-01',
    name: 'Nina',
    age: '22',
    sex: 'Female',
    ethnicity: 'Indigenous',
    size: 'M',
    height: "5'4\"",
    weight: '130 lbs',
    build: 'athletic',
    facialFeatures: 'strong features, warm expression',
    hairStyle: 'long straight',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'warm brown',
    fullDescription: 'Athletic 22-year-old woman with a strong presence and warm spirit. Her long straight black hair frames strong beautiful features and deep warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-white-l-01',
    name: 'Rachel',
    age: '24',
    sex: 'Female',
    ethnicity: 'White',
    size: 'L',
    height: "5'7\"",
    weight: '160 lbs',
    build: 'curvy athletic',
    facialFeatures: 'soft features, confident smile',
    hairStyle: 'medium layered',
    hairColor: 'auburn',
    eyeColor: 'green',
    skinTone: 'fair with freckles',
    fullDescription: 'Confident 24-year-old woman with curvy athletic build and natural charm. Her medium auburn hair with layers frames soft features, freckled fair skin, and bright green eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-white-s-01',
    name: 'Tyler',
    age: '20',
    sex: 'Male',
    ethnicity: 'White',
    size: 'S',
    height: "5'9\"",
    weight: '150 lbs',
    build: 'lean',
    facialFeatures: 'youthful face, light stubble',
    hairStyle: 'medium textured',
    hairColor: 'blonde',
    eyeColor: 'blue',
    skinTone: 'fair',
    fullDescription: 'Energetic 20-year-old man with a lean build and youthful appearance. His medium textured blonde hair is casually styled, with light stubble and bright blue eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-black-m-01',
    name: 'Jaylen',
    age: '22',
    sex: 'Male',
    ethnicity: 'Black',
    size: 'M',
    height: "5'11\"",
    weight: '175 lbs',
    build: 'athletic',
    facialFeatures: 'defined features, confident expression',
    hairStyle: 'short twist',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'dark brown',
    fullDescription: 'Athletic 22-year-old man with a confident presence and easy charisma. His short twist hairstyle is neatly maintained, with defined features and focused dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-hispanic-m-01',
    name: 'Marco',
    age: '23',
    sex: 'Male',
    ethnicity: 'Hispanic',
    size: 'M',
    height: "5'10\"",
    weight: '170 lbs',
    build: 'toned',
    facialFeatures: 'warm smile, trimmed beard',
    hairStyle: 'short wavy',
    hairColor: 'dark brown',
    eyeColor: 'brown',
    skinTone: 'tan',
    fullDescription: 'Friendly 23-year-old man with a toned build and warm personality. His short wavy dark brown hair and neatly trimmed beard complement his tan skin and warm brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-asian-s-01',
    name: 'Kevin',
    age: '21',
    sex: 'Male',
    ethnicity: 'Asian',
    size: 'S',
    height: "5'8\"",
    weight: '145 lbs',
    build: 'slim',
    facialFeatures: 'clean-cut, friendly expression',
    hairStyle: 'short styled',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'light',
    fullDescription: 'Studious 21-year-old man with a slim build and clean-cut appearance. His short styled black hair is neatly groomed, with a friendly expression and attentive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-indian-l-01',
    name: 'Rohan',
    age: '24',
    sex: 'Male',
    ethnicity: 'Indian',
    size: 'L',
    height: "5'11\"",
    weight: '185 lbs',
    build: 'solid muscular',
    facialFeatures: 'strong features, short beard',
    hairStyle: 'short with wave',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium brown',
    fullDescription: 'Strong 24-year-old man with a solid muscular build. His short black hair with natural wave and short beard frame strong features and confident dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-southeast-asian-m-01',
    name: 'Daniel',
    age: '22',
    sex: 'Male',
    ethnicity: 'Southeast Asian',
    size: 'M',
    height: "5'7\"",
    weight: '155 lbs',
    build: 'compact muscular',
    facialFeatures: 'round face, easy smile',
    hairStyle: 'short cropped',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'medium tan',
    fullDescription: 'Friendly 22-year-old man with a compact muscular build. His short cropped black hair is low-maintenance, with a round face and an easy-going smile and warm dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-indigenous-l-01',
    name: 'Kai',
    age: '23',
    sex: 'Male',
    ethnicity: 'Indigenous',
    size: 'L',
    height: "6'0\"",
    weight: '190 lbs',
    build: 'athletic broad',
    facialFeatures: 'strong jaw, focused expression',
    hairStyle: 'long tied back',
    hairColor: 'black',
    eyeColor: 'dark brown',
    skinTone: 'warm reddish-brown',
    fullDescription: 'Athletic 23-year-old man with a broad build and quiet confidence. His long black hair is tied back, with a strong jaw and focused dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-white-l-01',
    name: 'Brandon',
    age: '24',
    sex: 'Male',
    ethnicity: 'White',
    size: 'L',
    height: "6'1\"",
    weight: '195 lbs',
    build: 'muscular',
    facialFeatures: 'rugged features, full beard',
    hairStyle: 'short textured',
    hairColor: 'brown',
    eyeColor: 'hazel',
    skinTone: 'light tan',
    fullDescription: 'Strong 24-year-old man with a muscular build and rugged appeal. His short textured brown hair and full beard give him a mature look, with warm hazel eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-male-middle-eastern-m-01',
    name: 'Tariq',
    age: '22',
    sex: 'Male',
    ethnicity: 'Middle Eastern',
    size: 'M',
    height: "5'10\"",
    weight: '165 lbs',
    build: 'athletic lean',
    facialFeatures: 'strong jawline, defined brows, short groomed beard',
    hairStyle: 'short and styled',
    hairColor: 'dark brown',
    eyeColor: 'deep brown',
    skinTone: 'warm olive',
    fullDescription: 'Athletic 22-year-old man with a lean muscular build and confident presence. His short styled dark brown hair and groomed beard frame a strong jawline, with striking deep brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  },
  {
    id: 'young-adult-female-middle-eastern-m-01',
    name: 'Leila',
    age: '21',
    sex: 'Female',
    ethnicity: 'Middle Eastern',
    size: 'M',
    height: "5'5\"",
    weight: '130 lbs',
    build: 'graceful slender',
    facialFeatures: 'elegant features, arched brows, warm smile',
    hairStyle: 'long wavy',
    hairColor: 'dark brown',
    eyeColor: 'dark brown',
    skinTone: 'warm olive',
    fullDescription: 'Graceful 21-year-old woman with a slender build and elegant presence. Her long wavy dark brown hair frames elegant features with arched brows, warm olive skin, and expressive dark brown eyes.',
    version: '1.0',
    createdDate: '2024-01-15'
  }
];
